Repository ucsb-cs156-s21/proj-ucsb-cs-las, pull requests merged in 2020-12, with the labels that each got.

#56 6pm c svpa tutor assignment
  javascript/package-lock.json
  javascript/package.json
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentForm.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js
  javascript/src/main/pages/TutorAssignment/NewTutorAssignment.js
  javascript/src/main/pages/TutorAssignment/TutorAssignment.js
  javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
  javascript/src/main/utils/quarter.ts
  javascript/src/react-app-env.d.ts
  javascript/src/test/components/Courses/CourseTable.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentForm.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
  javascript/src/test/pages/TutorAssignment/NewTutorAssignment.test.js
  javascript/src/test/pages/TutorAssignment/TutorAssignment.test.js
  javascript/src/test/services/TutorAssignmentService.test.js
  javascript/src/test/utils/quarter.test.ts
  javascript/tsconfig.json
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
Labels: FIX ME, f20-6pm-c

#71 6pm b track logins
  javascript/package-lock.json
  javascript/src/main/App.js
  javascript/src/main/components/Admin/LoginTable.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/Admin/ViewLogins.js
  javascript/src/test/components/Admin/LoginTable.test.js
  javascript/src/test/pages/Admin/ViewLogins.test.js
  pom.xml
  src/main/java/edu/ucsb/ucsbcslas/controllers/LoginsController.java
  src/main/java/edu/ucsb/ucsbcslas/documents/Login.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/LoginsRepository.java
  src/main/java/edu/ucsb/ucsbcslas/services/Auth0MembershipService.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/LoginsControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/documents/LoginTests.java
  src/test/java/edu/ucsb/ucsbcslas/services/Auth0MembershipServiceTests.java
Labels: f20-6pm-b

#70 6pm b course tutor history, issue #69, backend routes
  javascript/src/main/components/Nav/AppNavbar.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
Labels: Ready for Staff Review, f20-6pm-b

#76 6pm b course tutor history frontend
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/TutorHistory/TutorHistoryForm.js
  javascript/src/main/pages/TutorHistory/TutorHistory.js
  javascript/src/main/services/TutorHistory/TutorHistoryService.js
  javascript/src/test/App.test.js
  javascript/src/test/components/TutorHistory/TutorHistoryForm.test.js
  javascript/src/test/pages/TutorHistory/TutorHistory.test.js
  javascript/src/test/services/TutorHistoryService.test.js
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
Labels: Ready for Staff Review, f20-6pm-b

#62 6pm d add sorting to courses
  .gitignore
  javascript/src/main/components/Courses/CourseTable.js
  javascript/src/main/pages/Courses/Courses.js
  javascript/src/test/components/Courses/CourseTable.test.js
Labels: Ready for Staff Review, f20-6pm-d

#63 6-pm-d: LL course form validation
  .gitignore
  javascript/src/main/components/Courses/CourseForm.js
  javascript/src/main/pages/Courses/NewCourse.js
  javascript/src/main/services/Courses/CourseService.js
  javascript/src/main/utils/CourseFormHelpers.js
  javascript/src/main/utils/fetch.js
  javascript/src/test/pages/Courses/NewCourse.test.js
  javascript/src/test/utils/CourseFormHelpers.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
Labels: Ready for Staff Review, f20-6pm-d

#68 6pm c crud tutor
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Tutor/TutorForm.js
  javascript/src/main/components/Tutor/TutorTable.js
  javascript/src/main/pages/Tutor/EditTutor.js
  javascript/src/main/pages/Tutor/NewTutor.js
  javascript/src/main/pages/Tutor/Tutor.js
  javascript/src/main/services/Tutor/TutorService.js
  javascript/src/test/components/Tutor/TutorForm.test.js
  javascript/src/test/components/Tutor/TutorTable.test.js
  javascript/src/test/pages/Tutor/EditTutor.test.js
  javascript/src/test/pages/Tutor/NewTutor.test.js
  javascript/src/test/pages/Tutor/Tutor.test.js
  javascript/src/test/services/TutorService.test.js
  src/main/java/edu/ucsb/ucsbcslas/advice/AuthControllerAdvice.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorController.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/TutorTests.java
Labels: FIX ME, f20-6pm-c

#60 6pm b tk filterbyquarter
  javascript/src/main/App.js
  javascript/src/main/components/Courses/CourseTable.js
  javascript/src/main/components/Courses/QuarterFilterForm.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/Admin/QuarterFilter.js
  javascript/src/main/pages/Courses/Courses.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/main/services/QuarterFilterService.js
  javascript/src/test/components/QuarterFilterForm.test.js
  javascript/src/test/pages/Home/Home.test.js
  javascript/src/test/pages/QuarterFilter.test.js
  javascript/src/test/services/QuarterFilterService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/ActiveQuarterController.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/ActiveQuarter.java
  src/main/java/edu/ucsb/ucsbcslas/entities/Admin.java
  src/main/java/edu/ucsb/ucsbcslas/models/Course.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/ActiveQuarterRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/ActiveQuarterControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/ActiveQuarterTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/AdminTests.java
Labels: Ready for Staff Review, f20-6pm-b

#72 6pm d upload and download feature
  javascript/package-lock.json
  javascript/package.json
  javascript/src/main/pages/Courses/Courses.js
  pom.xml
Labels: Ready for Staff Review, f20-6pm-d

#82 6pm d BUG FIX to csv download, repair missing course number column
  javascript/src/main/pages/Courses/Courses.js
Labels: 10, bug, f20-6pm-d

#74 6pm-c-svpaTutorAssignmentUD
  javascript/src/main/App.js
  javascript/src/main/components/Courses/CourseForm.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Tutor/TutorTable.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentForm.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js
  javascript/src/main/pages/TutorAssignment/EditTutorAssignment.js
  javascript/src/main/pages/TutorAssignment/NewTutorAssignment.js
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
  javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
  javascript/src/main/utils/CourseFormHelpers.js
  javascript/src/test/components/Courses/CourseForm.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentForm.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
  javascript/src/test/pages/TutorAssignment/EditTutorAssignment.test.js
  javascript/src/test/pages/TutorAssignment/NewTutorAssignment.test.js
  javascript/src/test/pages/TutorAssignment/TutorAssignment.test.js
  javascript/src/test/pages/TutorHistory/TutorHistory.test.js
  javascript/src/test/services/TutorAssignmentService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
Labels: Ready for Staff Review, f20-6pm-c

#66 6pm a course list for current quarter
  javascript/src/main/App.js
  javascript/src/main/components/Courses/CourseDetail.js
  javascript/src/main/components/Courses/CourseList.js
  javascript/src/main/pages/About/About.js
  javascript/src/main/pages/Courses/CourseShow.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/test/App.test.js
  javascript/src/test/components/Courses/CourseDetail.test.js
  javascript/src/test/components/Courses/CourseList.test.js
  javascript/src/test/components/Courses/CourseTable.test.js
  javascript/src/test/pages/Courses/CourseShow.test.js
  javascript/src/test/pages/Courses/Courses.test.js
  javascript/src/test/pages/Home/Home.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/OnlineOfficeHoursRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
Labels: 40, f20-6pm-a

#79 6pm a office hour table
  javascript/src/main/components/Courses/CourseDetail.js
  javascript/src/main/components/Courses/CourseList.js
  javascript/src/main/pages/Courses/CourseShow.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/test/components/Courses/CourseDetail.test.js
  javascript/src/test/components/Courses/CourseForm.test.js
  javascript/src/test/components/Courses/CourseList.test.js
  javascript/src/test/pages/Courses/CourseShow.test.js
  javascript/src/test/pages/Courses/Courses.test.js
  javascript/src/test/pages/Home/Home.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/models/TutorAssignmentOfficeHourView.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/OnlineOfficeHoursRepository.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/models/TutorAssignmentOfficeHourViewTest.java
Labels: Ready for Staff Review, f20-6pm-a

#75 6pm c office hours tutor assignment
  .gitignore
  javascript/src/main/App.js
  javascript/src/main/components/Courses/CourseTable.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
  javascript/src/main/pages/OfficeHours/NewOfficeHours.js
  javascript/src/main/pages/OfficeHours/OfficeHours.js
  javascript/src/main/pages/TutorAssignment/NewTutorAssignment.js
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
  javascript/src/main/services/OfficeHours/OfficeHourService.js
  javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/components/OfficeHours/OfficeHourTable.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentForm.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
  javascript/src/test/pages/OfficeHours/OfficeHours.test.js
  javascript/src/test/services/OfficeHours/OfficeHourService.test.js
  javascript/src/test/services/TutorAssignmentService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/OnlineOfficeHours.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/OnlineOfficeHoursRepository.java
  src/main/resources/data.sql.SAMPLE
  src/test/java/edu/ucsb/ucsbcslas/DemoApplicationTests.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java
Labels: Ready for Staff Review, TEAM DONE, f20-6pm-c
