Repository ucsb-cs156-s21/proj-ucsb-cs-las, pull requests merged in 2021-03, with the labels that each got.

#133 Use ant instead of maven to copy secrets
  pom.xml
Labels: staff-PR

#127 EM - Implemented email links
  javascript/src/main/components/Courses/CourseTable.js
Labels: 5, w21-7pm-1

#125 Updated footer message 6pm-3
  javascript/src/main/components/Footer/AppFooter.js
  javascript/src/test/components/Footer/AppFooter.test.js
Labels: 5, w21-6pm-3

#135 6pm 1 fix about page
  javascript/package-lock.json
  javascript/src/main/pages/About/About.js
  src/main/resources/data.sql.SAMPLE
Labels: 5, w21-6pm-1

#129 pb: changed title of web page to 'UCSB CS LAs', completing issue #93
  javascript/public/index.html
Labels: FIX ME-please respond to code review, w21-6pm-3

#134 6pm 1 office hours table
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
Labels: Ready for Staff Review, w21-6pm-1

#126 make course table rows alternate in color like admin panel table
  javascript/.env.local.SAMPLE
  javascript/.env.production.SAMPLE
  javascript/src/main/components/Courses/CourseTable.js
Labels: FIX ME-please respond to code review, w21-7pm-1

#138 6pm 3 Fix course edit not converting quarter input
  javascript/src/main/components/Courses/CourseForm.js
  javascript/src/test/components/Courses/CourseForm.test.js
Labels: 5, w21-6pm-3

#137 mg - added margin to 'New Office Hour' button in OfficeHours.js
  javascript/src/main/pages/OfficeHours/OfficeHours.js
Labels: 5, Ready for Staff Review, w21-6pm-1

#131 6pm 3 zoom link clickable
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
  javascript/src/test/components/OfficeHours/OfficeHourTable.test.js
Labels: Ready for Staff Review, w21-6pm-3

#140 6pm 1 office hours time format
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/utils/OfficeHourFormHelpers.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
  javascript/src/test/utils/OfficeHourFormHelpers.test.js
Labels: w21-6pm-1

#139 7pm-1 make tutor assignment column sort
  javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
Labels: w21-7pm-1

#143 6pm 1 zoom validation for office hours table
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/utils/OfficeHourFormHelpers.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
  javascript/src/test/utils/OfficeHourFormHelpers.test.js
Labels: 20, w21-6pm-1

#155 6pm 1 drop down menu (and zoom room link optional)
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/utils/OfficeHourFormHelpers.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
  javascript/src/test/utils/OfficeHourFormHelpers.test.js
Labels: w21-6pm-1

#153 AL - Remove commented code from #68
  javascript/src/main/pages/Tutor/Tutor.js
  javascript/src/test/components/Tutor/TutorTable.test.js
  javascript/src/test/pages/Tutor/Tutor.test.js
Labels: staff-PR

#159 pb: course tables have proper quarter filter
  javascript/src/main/components/Courses/CourseList.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/main/utils/FromFormat.js
Labels: w21-6pm-3

#152 6pm 3 course link - in Courses page, the Course numbers cells in the "name" column now link to the courses show page
  javascript/src/main/components/Courses/CourseList.js
  javascript/src/main/components/Courses/CourseTable.js
Labels: FIX ME-staff review, w21-6pm-3

#163 6pm 1 tutor table sortable - can sort the Tutor table on any of the columns
  javascript/src/main/components/Tutor/TutorTable.js
  javascript/src/main/pages/Tutor/Tutor.js
  javascript/src/test/pages/Tutor/Tutor.test.js
  src/main/resources/application.properties
Labels: w21-6pm-1

#164 jv - remove browser false option in eslint config
  javascript/.eslintrc.json
Labels: staff-PR

#162 6pm 3 csv upload - added button to upload/download CSV of courses
  javascript/src/main/components/Courses/CourseCSVButton.js
  javascript/src/main/pages/Courses/Courses.js
  javascript/src/main/services/Courses/UploadCsv.js
  javascript/src/test/components/Courses/CourseCSVButton.test.js
  javascript/src/test/services/CourseService.test.js
  pom.xml
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/models/Course.java
  src/main/java/edu/ucsb/ucsbcslas/services/CSVToObjectService.java
  src/main/java/edu/ucsb/ucsbcslas/services/CSVToObjectServiceImpl.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
Labels: 40, w21-6pm-3

#160 6pm 3 quarter filter- in quarter filter page, can only search courses using correct quarter format (e.g 'W21')
  javascript/src/main/components/Courses/QuarterFilterForm.js
  javascript/src/main/services/QuarterFilterService.js
  javascript/src/test/components/Courses/QuarterFilterForm.test.js
  javascript/src/test/components/QuarterFilterForm.test.js
  javascript/src/test/pages/QuarterFilter.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/ActiveQuarterController.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/ActiveQuarterControllerTests.java
Labels: Ready for Staff Review, w21-6pm-3

#161 7pm 1 show next three office hour time
  javascript/package-lock.json
  javascript/src/main/components/Courses/CourseDetail.js
  javascript/src/main/components/Courses/CourseDetailOfficeHours.js
  javascript/src/main/pages/Courses/CourseShow.js
  javascript/src/test/components/Courses/CourseDetailOfficeHours.test.js
  javascript/src/test/pages/Courses/CourseShow.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
  src/main/java/edu/ucsb/ucsbcslas/models/TutorAssignmentOfficeHourView.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/CourseControllerTests.java
Labels: w21-7pm-1

#168 6pm 1 CSV Upload for Tutor
  javascript/src/main/components/Tutor/TutorCSVButton.js
  javascript/src/main/pages/Tutor/Tutor.js
  javascript/src/main/services/Tutor/TutorService.js
  javascript/src/test/components/Tutor/TutorCSVButton.test.js
  javascript/src/test/pages/Tutor/Tutor.test.js
  javascript/src/test/services/TutorService.test.js
  pom.xml
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/Tutor.java
  src/main/java/edu/ucsb/ucsbcslas/services/CSVToObjectService.java
  src/main/java/edu/ucsb/ucsbcslas/services/CSVToObjectServiceImpl.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorControllerTests.java
Labels: w21-6pm-1

#169 Replace tutor assignment id entry with a user friendly component
  javascript/.storybook/preview.js
  javascript/package-lock.json
  javascript/package.json
  javascript/src/index.js
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentSelect.js
  javascript/src/main/services/selectorSupport.js
  javascript/src/stories/components/TutorAssignment/TutorAssignmentSelect.stories.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentSelect.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
  javascript/src/test/services/selectorSupport.test.js
Labels: staff-PR
