Repository ucsb-cs156-s21/proj-ucsb-cs-las, pull requests merged in 2021-06, with the labels that each got.

#300 6pm 3 tutor notes backend only
  lombok.config
  pom.xml
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorNotesController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorNotes.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/OnlineOfficeHoursRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorNotesRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorNotesControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/TutorNotesTests.java
Labels: s21-6pm-3-tutor

#307 pc/wv - hot fix for deleting tutor assignment
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
Labels: staff-PR

#309 6pm-4-Fixed link issue on office hours where the link would go outside of the table (Remade PR)
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
  javascript/src/test/components/OfficeHours/OfficeHourTable.test.js
Labels: FIX ME-team member review, S21-6pm-4-CSV

#310 6pm-3-yl - updated caniuse via npx browerslist@latest --update-db
  javascript/package-lock.json
Labels: s21-6pm-3-tutor

#281 6pm-4-csv tutor assignment upload
  javascript/src/main/components/TutorAssignment/TutorAssignmentCSVButton.js
  javascript/src/main/pages/Tutor/Tutor.js
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
  javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
  javascript/src/test/pages/TutorAssignment/TutorAssignment.test.js
  javascript/src/test/pages/TutorAssignment/TutorAssignmentCSVButton.test.js
  javascript/src/test/services/TutorAssignmentService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java
  src/main/java/edu/ucsb/ucsbcslas/models/TutorAssignmentModel.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
  src/main/java/edu/ucsb/ucsbcslas/services/CSVToObjectService.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/models/TutorAssignmentModelTests.java
Labels: 40, S21-6pm-4-CSV

#305 6pm-2-add delete button in room slot table
  javascript/src/main/components/RoomSlots/RoomSlotTable.js
  javascript/src/main/pages/RoomSlots/RoomSlots.js
  javascript/src/main/services/RoomSlots/RoomSlotService.js
  javascript/src/test/components/RoomSlots/RoomSlotTable.test.js
  javascript/src/test/services/RoomSlotService.test.js
Labels: s21-6pm-2-f2f

#312 6pm-2 room slot selector
  javascript/src/fixtures/roomSlotFixtures.js
  javascript/src/main/components/RoomSlots/RoomSlotSelector.js
  javascript/src/stories/components/RoomSlots/RoomSlotSelector.stories.js
  javascript/src/test/components/RoomSlots/RoomSlotSelector.test.js
Labels: 10, s21-6pm-2-f2f

#308 6pm 3 tutor notes page create only
  javascript/src/fixtures/tutorNotesFixtures.js
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/OfficeHours/OfficeHoursSelector.js
  javascript/src/main/components/TutorNotes/TutorNotesForm.js
  javascript/src/main/components/TutorNotes/TutorNotesTable.js
  javascript/src/main/pages/TutorNotes/NewTutorNotes.js
  javascript/src/main/pages/TutorNotes/TutorNotes.js
  javascript/src/main/services/TutorNotes/TutorNotesService.js
  javascript/src/stories/components/TutorNotes/TutorNotesTable.stories.js
  javascript/src/test/components/TutorNotes/TutorNotesForm.test.js
  javascript/src/test/components/TutorNotes/TutorNotesTable.test.js
  javascript/src/test/pages/TutorNotes/NewTutorNotes.test.js
  javascript/src/test/pages/TutorNotes/TutorNotes.test.js
Labels: s21-6pm-3-tutor

#316 6pm-3 Bug fix, backend was doubling entries to database; removed that issue
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorNotesController.java
Labels: s21-6pm-3-tutor
