Repository ucsb-cs156-s21/proj-ucsb-cs-las, pull requests merged in 2021-05, with the labels that each got.

#207 dw/rb - changed favicon s21-6pm-4
  javascript/public/favicon.ico
  javascript/public/index.html
Labels: FIX ME-code review issues

#217 6pm-4- add credit for favicon and logo
  javascript/src/main/components/Footer/AppFooter.js
Labels: 5

#215 KW - 6pm-1 Added spacing between the New Course button and the table
  javascript/src/main/pages/Courses/Courses.js
Labels: FIX ME-staff review, FIX ME-team member review, s21-6pm-1

#216 6pm 2 office hours sortable - rc/rt
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
Labels: FIX ME-staff review, FIX ME-team member review, s21-6pm-2

#205 KH/OB - 6pm-1 changed footer height to auto instead of 100px
  javascript/src/main/App.css
Labels: FIX ME-team member review, s21-6pm-1

#228 wp - 6pm-2 Tutor Assignment Spacing
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
Labels: s21-6pm-2

#208 nc/ar - 6pm-2 add header to view logins subpage
  javascript/src/main/pages/Admin/ViewLogins.js
Labels: FIX ME-staff review, FIX ME-team member review, s21-6pm-2

#209 yl/mb - 6pm-3 - Login Admin Table Sortable
  javascript/src/main/components/Admin/LoginTable.js
Labels: 5, s21-6pm-3

#214 ZW - AN - 6pm-3 - Refactor Course Table
  javascript/.storybook/preview.js
  javascript/src/index.js
  javascript/src/main/components/Courses/CourseTable.js
  javascript/src/test/components/Courses/CourseTable.test.js
Labels: s21-6pm-3

#236 rc/wp - 6pm-2 Add Swagger support to enable easier development of backend apis
  pom.xml
  src/main/java/edu/ucsb/ucsbcslas/config/SecurityConfig.java
  src/main/java/edu/ucsb/ucsbcslas/config/SpringFoxConfig.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/ReactController.java
  src/main/resources/application.properties
Labels: FIX ME-staff review, s21-6pm-2

#233 dw - 6pm-4-Add download csv button for Office Hours
  javascript/src/main/pages/OfficeHours/OfficeHours.js
Labels: FIX ME-team member review, S21-6pm-4-CSV

#232 rt - 6pm-2 Use Bootstrap classes for styling on Admin/View Logins page and Tutor Assignments button
  javascript/src/main/pages/Admin/ViewLogins.js
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
Labels: s21-6pm-2

#240 hl - 6pm-4 add CSV button for downloading all logins
  javascript/src/main/pages/Admin/ViewLogins.js
Labels: S21-6pm-4-CSV

#243 dw - 6pm-4 Add download button for a csv file of all Admins
  javascript/src/main/pages/Admin/Admin.js
Labels: S21-6pm-4-CSV

#242 mc/zw/an-6pm 3 tutor notes database implementation
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorNotes.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorNotesRepository.java
  src/test/java/edu/ucsb/ucsbcslas/entities/TutorNotesTests.java
Labels: FIX ME-needs PR description, FIX ME-team member review, s21-6pm-3-tutor

#246 dw - Add a download csv button to download a csv of all users
  javascript/src/main/pages/Admin/Admin.js
Labels: FIX ME-team member review, S21-6pm-4-CSV

#253 6pm-4-add download csv button on tutors page
  javascript/src/main/pages/Tutor/Tutor.js
Labels: S21-6pm-4-CSV

#250 6pm 2 room slot database
  src/main/java/edu/ucsb/ucsbcslas/entities/RoomSlot.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/RoomSlotRepository.java
  src/test/java/edu/ucsb/ucsbcslas/entities/RoomSlotTests.java
Labels: FIX ME-please respond to code review, s21-6pm-2-f2f

#269 6pm-2 Implemented Room Slot CRUD in the endpoint
  src/main/java/edu/ucsb/ucsbcslas/config/ObjectMapperConfig.java
  src/main/java/edu/ucsb/ucsbcslas/controllers/RoomSlotController.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/RoomSlotControllerTests.java
Labels: FIX ME-team member review, s21-6pm-2-f2f

#268 dw - 6pm-4-add a login count on view logins page
  javascript/src/main/pages/Admin/ViewLogins.js
Labels: S21-6pm-4-CSV

#255 rb - 6pm-4 - add a Download CSV button that downloads a CSV containing all ULA Tutor assignments
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
Labels: 10, S21-6pm-4-CSV

#272 6pm-1 cx -Modified footer so that it will stick on the bottom
  javascript/src/main/App.css
  javascript/src/main/App.js
Labels: FIX ME-please respond to code review, s21-6pm-1-crud

#282 6pm-1 cx -replace custom ccs with existing bootstrap
  javascript/src/main/App.css
  javascript/src/main/App.js
Labels: s21-6pm-1-crud

#257 KW/CX 6pm-1 update office hour
  javascript/src/main/App.js
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
  javascript/src/main/pages/OfficeHours/EditOfficeHours.js
  javascript/src/main/services/OfficeHours/OfficeHourService.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/components/OfficeHours/OfficeHourTable.test.js
  javascript/src/test/pages/OfficeHours/EditOfficeHours.test.js
  javascript/src/test/services/OfficeHours/OfficeHourService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java
Labels: s21-6pm-1-crud

#273 6pm-1 Added spacing on the logins page
  javascript/src/main/pages/Admin/ViewLogins.js
Labels: 5, s21-6pm-1-crud

#284 KW/CX 6pm-1 added tutor name, course name, and quarter to office hour table
  javascript/src/main/components/OfficeHours/OfficeHourTable.js
Labels: s21-6pm-1-crud

#270 6pm-4-add upload CSV to Office Hours
  javascript/src/main/components/OfficeHours/OfficeHourCSVButton.js
  javascript/src/main/pages/OfficeHours/OfficeHours.js
  javascript/src/main/services/OfficeHours/UploadCSV.js
  javascript/src/test/components/OfficeHours/OfficeHourCSVButton.test.js
  javascript/src/test/pages/OfficeHours/OfficeHours.test.js
  javascript/src/test/services/OfficeHours/OfficeHourService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
  src/main/java/edu/ucsb/ucsbcslas/entities/OnlineOfficeHours.java
  src/main/java/edu/ucsb/ucsbcslas/entities/Tutor.java
  src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java
  src/main/java/edu/ucsb/ucsbcslas/models/Course.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/OnlineOfficeHoursTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/TutorAssignmentTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/TutorTests.java
  src/test/java/edu/ucsb/ucsbcslas/models/CourseTests.java
Labels: 40, S21-6pm-4-CSV

#287 6pm-1 CX/KW -user couldn't edit tutor name when they update office hour
  javascript/package.json
  javascript/src/fixtures/tutorAssignmentFixtures.js
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/components/TutorAssignment/TutorAssignmentDisplay.js
  javascript/src/stories/components/TutorAssignment/TutorAssignmentDisplay.stories.js
  javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
  javascript/src/test/pages/OfficeHours/EditOfficeHours.test.js
  javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js
Labels: FIX ME-failing tests, Ready for Staff Review, S21, s21-6pm-1-crud

#286 6pm 1 delete tutor assignment
  javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js
  javascript/src/main/pages/TutorAssignment/TutorAssignments.js
  javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
  javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
  javascript/src/test/pages/TutorAssignment/TutorAssignment.test.js
  javascript/src/test/services/TutorAssignmentService.test.js
  src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentControllerTests.java
Labels: 20, s21-6pm-1-crud

#298 6pm 3 office hours member route
  src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/OnlineOfficeHoursRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java
Labels: s21-6pm-3-tutor

#275 6pm-2 create frontend pages to add and display room slots
  javascript/src/main/App.js
  javascript/src/main/components/Courses/CourseForm.js
  javascript/src/main/components/Courses/QuarterFilterForm.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/OfficeHours/OfficeHourForm.js
  javascript/src/main/components/RoomSlots/RoomSlotForm.js
  javascript/src/main/components/RoomSlots/RoomSlotTable.js
  javascript/src/main/pages/OfficeHours/OfficeHours.js
  javascript/src/main/pages/RoomSlots/NewRoomSlot.js
  javascript/src/main/pages/RoomSlots/RoomSlots.js
  javascript/src/main/services/QuarterFilterService.js
  javascript/src/main/services/RoomSlots/RoomSlotService.js
  javascript/src/main/utils/CourseFormHelpers.js
  javascript/src/main/utils/FormHelpers.js
  javascript/src/main/utils/OfficeHourFormHelpers.js
  javascript/src/main/utils/RoomSlotFormHelpers.js
  javascript/src/main/utils/RoomSlotTableHelpers.js
  javascript/src/test/components/RoomSlots/RoomSlotForm.test.js
  javascript/src/test/components/RoomSlots/RoomSlotTable.test.js
  javascript/src/test/pages/RoomSlots/NewRoomSlot.test.js
  javascript/src/test/pages/RoomSlots/RoomSlots.test.js
  javascript/src/test/services/RoomSlotService.test.js
  javascript/src/test/utils/CourseFormHelpers.test.js
  javascript/src/test/utils/FormHelpers.test.js
  javascript/src/test/utils/OfficeHourFormHelpers.test.js
  javascript/src/test/utils/RoomSlotFormHelpers.test.js
  javascript/src/test/utils/RoomSlotTableHelpers.test.js
  src/main/java/edu/ucsb/ucsbcslas/config/ObjectMapperConfig.java
  src/main/java/edu/ucsb/ucsbcslas/entities/RoomSlot.java
  src/main/java/edu/ucsb/ucsbcslas/repositories/RoomSlotRepository.java
  src/test/java/edu/ucsb/ucsbcslas/controllers/RoomSlotControllerTests.java
  src/test/java/edu/ucsb/ucsbcslas/entities/RoomSlotTests.java
Labels: FIX ME-team member review, s21-6pm-2-f2f
